name: Exploration CI CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # FRONTEND
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      # BACKEND
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # TEST (safe mode)
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test || echo "No tests or failed tests (ignored for CI demo)"

      # BUILD CHECK (frontend)
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build || echo "No build script"

      # SIMPLE SUCCESS MESSAGE
      - name: CI Success
        run: echo "CI Pipeline Executed Successfully 🎉"
