name: 🚀 Exploration CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 📥 Step 1: Checkout Code
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      # 🟢 Step 2: Setup Node
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 📦 Step 3: Install Dependencies
      - name: 📦 Install Dependencies
        run: npm install

      # 🧪 Step 4: Run Tests
      - name: 🧪 Run Tests
        run: npm test || echo "⚠️ No tests found or failed (ignored for CI demo), Useful If we want to create feature for our website we can write the test files"

      # 🏗️ Step 5: Build Check
      - name: 🏗️ Build Check
        run: npm run build || echo "⚠️ No build script found"

      # 🎉 Step 6: Success Message
      - name: 🎉 CI Success
        run: echo "✅ CI Pipeline Executed Successfully 🎉"
